"""Render a generated Document to PDF (FR-F). Uses fpdf2 core fonts, which are
latin-1 only — non-latin characters used by our templates (₹, em-dash, ·) are
transliterated rather than dropped, and anything else falls back to '?'."""
from fpdf import FPDF

from ..clock import now_ist

_TRANSLIT = {
    "₹": "Rs ",
    "—": "-",
    "–": "-",
    "·": "-",
    "→": "->",
    "×": "x",
    "’": "'",
    "‘": "'",
    "“": '"',
    "”": '"',
    "…": "...",
}


def _latin(text: str) -> str:
    for k, v in _TRANSLIT.items():
        text = text.replace(k, v)
    return text.encode("latin-1", "replace").decode("latin-1")


def render_pdf(title: str, meta_line: str, body: str) -> bytes:
    pdf = FPDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    cell = dict(new_x="LMARGIN", new_y="NEXT")  # keep the cursor at the left edge
    pdf.set_font("helvetica", "B", 14)
    pdf.multi_cell(0, 8, _latin(title), **cell)
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(110, 110, 110)
    pdf.multi_cell(0, 5, _latin(meta_line), **cell)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    pdf.set_font("courier", "", 10)
    pdf.multi_cell(0, 5, _latin(body), **cell)

    pdf.ln(6)
    pdf.set_font("helvetica", "I", 8)
    pdf.set_text_color(110, 110, 110)
    pdf.multi_cell(0, 4, _latin(f"Generated by Paper on {now_ist():%d %b %Y %H:%M} IST"), **cell)
    return bytes(pdf.output())
