"""baseline schema

Revision ID: a64b6c407af7
Revises: 
Create Date: 2026-07-02 21:51:33.195159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a64b6c407af7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('actor_user_id', sa.String(length=32), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_actor_user_id'), ['actor_user_id'], unique=False)

    op.create_table('service_providers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('CS', 'CA', 'LAWYER', 'VALUER', 'RTA', 'FUND_ADMIN', name='providercategory'), nullable=False),
    sa.Column('firm', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('profile', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('COMPANY', 'FUND', 'FIRM', name='tenanttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('legal_entities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('PVT_LTD', 'LLP', 'OPC', 'FUND', 'SPV', name='entitytype'), nullable=False),
    sa.Column('cin', sa.String(length=32), nullable=True),
    sa.Column('pan', sa.String(length=16), nullable=True),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legal_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_entities_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uq_user_tenant')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('admin_subscriptions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.Enum('BASIC', 'GROWTH', 'SCALE', name='subscriptiontier'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_subscriptions_entity_id'), ['entity_id'], unique=True)

    op.create_table('charges_register',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('holder', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('charge_type', sa.String(length=120), nullable=False),
    sa.Column('created_on', sa.Date(), nullable=False),
    sa.Column('satisfied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('charges_register', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charges_register_entity_id'), ['entity_id'], unique=False)

    op.create_table('compliance_obligations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('form_code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('period_label', sa.String(length=32), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DUE', 'IN_PREP', 'FILED', 'ACKNOWLEDGED', name='obligationstatus'), nullable=False),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('srn', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'form_code', 'period_label', name='uq_obligation')
    )
    with op.batch_alter_table('compliance_obligations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_obligations_entity_id'), ['entity_id'], unique=False)

    op.create_table('convertible_instruments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('investor_name', sa.String(length=255), nullable=False),
    sa.Column('investor_email', sa.String(length=255), nullable=True),
    sa.Column('instrument_type', sa.Enum('SAFE', 'CONVERTIBLE_NOTE', name='instrumenttype'), nullable=False),
    sa.Column('principal', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('valuation_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('discount_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('mfn', sa.Boolean(), nullable=False),
    sa.Column('interest_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OUTSTANDING', 'CONVERTED', 'CANCELLED', name='instrumentstatus'), nullable=False),
    sa.Column('converted_shares', sa.Integer(), nullable=True),
    sa.Column('stakeholder_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('convertible_instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_convertible_instruments_entity_id'), ['entity_id'], unique=False)

    op.create_table('counterparties',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('CUSTOMER', 'VENDOR', 'PARTNER', name='counterpartykind'), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counterparties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counterparties_entity_id'), ['entity_id'], unique=False)

    op.create_table('data_rooms',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_rooms_entity_id'), ['entity_id'], unique=False)

    op.create_table('directors_officers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('din', sa.String(length=16), nullable=True),
    sa.Column('designation', sa.Enum('DIRECTOR', 'MANAGING_DIRECTOR', 'WHOLE_TIME_DIRECTOR', 'INDEPENDENT_DIRECTOR', 'NOMINEE_DIRECTOR', 'COMPANY_SECRETARY', 'CFO', name='directordesignation'), nullable=False),
    sa.Column('appointed_on', sa.Date(), nullable=False),
    sa.Column('resigned_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('directors_officers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_directors_officers_entity_id'), ['entity_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'SIGNED', name='documentstatus'), nullable=False),
    sa.Column('template_key', sa.String(length=64), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=64), nullable=True),
    sa.Column('subject_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_entity_id'), ['entity_id'], unique=False)

    op.create_table('esop_schemes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('pool_size', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('esop_schemes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_esop_schemes_entity_id'), ['entity_id'], unique=False)

    op.create_table('financial_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('monthly_burn', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'period', name='uq_entity_period')
    )
    with op.batch_alter_table('financial_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_snapshots_entity_id'), ['entity_id'], unique=False)

    op.create_table('funds',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('sebi_category', sa.Enum('CAT_I', 'CAT_II', 'CAT_III', name='sebicategory'), nullable=False),
    sa.Column('structure', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('target_corpus', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('carry_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('hurdle_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('funds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_funds_entity_id'), ['entity_id'], unique=True)

    op.create_table('investor_access',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('stakeholder_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investor_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investor_access_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_investor_access_entity_id'), ['entity_id'], unique=False)

    op.create_table('investor_updates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investor_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investor_updates_entity_id'), ['entity_id'], unique=False)

    op.create_table('meetings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('BOARD', 'AGM', 'EGM', name='meetingtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('quorum', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'HELD', 'CANCELLED', name='meetingstatus'), nullable=False),
    sa.Column('minutes', sa.Text(), nullable=True),
    sa.Column('notice_document_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_entity_id'), ['entity_id'], unique=False)

    op.create_table('prospect_investors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('firm', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('stage', sa.Enum('CONTACTED', 'MEETING', 'DILIGENCE', 'TERM_SHEET', 'COMMITTED', 'PASSED', name='pipelinestage'), nullable=False),
    sa.Column('check_size', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('round_id', sa.String(length=32), nullable=True),
    sa.Column('last_contact', sa.Date(), nullable=True),
    sa.Column('commitment_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prospect_investors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prospect_investors_entity_id'), ['entity_id'], unique=False)

    op.create_table('registrations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.Enum('GST', 'PROFESSIONAL_TAX', 'SHOPS_ESTABLISHMENT', 'PF', 'ESIC', name='registrationkind'), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registrations_entity_id'), ['entity_id'], unique=False)

    op.create_table('sbo_register',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pan', sa.String(length=16), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('nature', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sbo_register', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sbo_register_entity_id'), ['entity_id'], unique=False)

    op.create_table('security_classes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('EQUITY', 'CCPS', 'CCD', 'OPTION_POOL', 'SAFE', 'WARRANT', name='securitykind'), nullable=False),
    sa.Column('par_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('pref_multiple', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('participating', sa.Boolean(), nullable=False),
    sa.Column('seniority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_classes_entity_id'), ['entity_id'], unique=False)

    op.create_table('service_engagements',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'ACCEPTED', 'IN_PROGRESS', 'DELIVERED', 'CLOSED', name='engagementstatus'), nullable=False),
    sa.Column('deliverable_doc_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_engagements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_engagements_entity_id'), ['entity_id'], unique=False)

    op.create_table('spvs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('sponsor', sa.String(length=255), nullable=False),
    sa.Column('target_company', sa.String(length=255), nullable=False),
    sa.Column('structure', sa.String(length=32), nullable=False),
    sa.Column('portco_entity_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['portco_entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spvs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spvs_entity_id'), ['entity_id'], unique=True)

    op.create_table('stakeholders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('FOUNDER', 'INVESTOR', 'EMPLOYEE', 'ENTITY', name='stakeholdertype'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stakeholders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stakeholders_entity_id'), ['entity_id'], unique=False)

    op.create_table('startup_recognition',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('NOT_APPLIED', 'APPLIED', 'RECOGNISED', 'REJECTED', name='recognitionstatus'), nullable=False),
    sa.Column('dpiit_number', sa.String(length=64), nullable=True),
    sa.Column('recognised_on', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('startup_recognition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_startup_recognition_entity_id'), ['entity_id'], unique=True)

    op.create_table('tax_benefit_applications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('SECTION_80IAC', 'ANGEL_TAX_EXEMPTION', name='benefittype'), nullable=False),
    sa.Column('status', sa.Enum('NOT_APPLIED', 'APPLIED', 'APPROVED', 'REJECTED', name='benefitstatus'), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_benefit_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_benefit_applications_entity_id'), ['entity_id'], unique=False)

    op.create_table('tax_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('GST', 'TDS', 'FORM16', 'ITR', 'OTHER', name='taxrecordtype'), nullable=False),
    sa.Column('period_label', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('filed_on', sa.Date(), nullable=True),
    sa.Column('document_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_records_entity_id'), ['entity_id'], unique=False)

    op.create_table('team_members',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('employment_type', sa.Enum('EMPLOYEE', 'CONTRACTOR', 'ADVISOR', name='employmenttype'), nullable=False),
    sa.Column('joined_on', sa.Date(), nullable=True),
    sa.Column('left_on', sa.Date(), nullable=True),
    sa.Column('stakeholder_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_entity_id'), ['entity_id'], unique=False)

    op.create_table('valuation_reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('method', sa.Enum('RULE_11UA', 'FEMA', 'FAIR_VALUE', name='valuationmethod'), nullable=False),
    sa.Column('valuer_name', sa.String(length=255), nullable=True),
    sa.Column('fmv_per_share', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('basis', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'FINAL', name='valuationstatus'), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('valuation_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valuation_reports_entity_id'), ['entity_id'], unique=False)

    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('definition_key', sa.String(length=64), nullable=False),
    sa.Column('definition_version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'CANCELLED', name='runstatus'), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_runs_entity_id'), ['entity_id'], unique=False)

    op.create_table('admin_audits',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('subscription_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('CORPORATE_AUDIT', 'PRE_DILIGENCE', 'CLEANUP', name='audittype'), nullable=False),
    sa.Column('period_label', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', name='auditstatus'), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['admin_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_audits_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('admin_touchpoints',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('subscription_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('attendee', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['admin_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_touchpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_touchpoints_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('agenda_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agenda_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agenda_items_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('buyback_transactions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('security_class_id', sa.String(length=32), nullable=False),
    sa.Column('stakeholder_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['security_class_id'], ['security_classes.id'], ),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buyback_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buyback_transactions_entity_id'), ['entity_id'], unique=False)

    op.create_table('capital_calls',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('fund_id', sa.String(length=32), nullable=False),
    sa.Column('call_no', sa.Integer(), nullable=False),
    sa.Column('pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capital_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capital_calls_fund_id'), ['fund_id'], unique=False)

    op.create_table('contracts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('counterparty_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'EXPIRED', 'TERMINATED', name='contractstatus'), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_counterparty_id'), ['counterparty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_entity_id'), ['entity_id'], unique=False)

    op.create_table('conversion_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('stakeholder_id', sa.String(length=32), nullable=False),
    sa.Column('from_class_id', sa.String(length=32), nullable=False),
    sa.Column('to_class_id', sa.String(length=32), nullable=False),
    sa.Column('from_quantity', sa.Integer(), nullable=False),
    sa.Column('to_quantity', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['from_class_id'], ['security_classes.id'], ),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholders.id'], ),
    sa.ForeignKeyConstraint(['to_class_id'], ['security_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversion_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversion_events_entity_id'), ['entity_id'], unique=False)

    op.create_table('corporate_actions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('security_class_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('SPLIT', 'BONUS', name='corporateactiontype'), nullable=False),
    sa.Column('numerator', sa.Integer(), nullable=False),
    sa.Column('denominator', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['security_class_id'], ['security_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corporate_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corporate_actions_entity_id'), ['entity_id'], unique=False)

    op.create_table('data_room_access_grants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('data_room_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('permissions', sa.String(length=32), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_room_id'], ['data_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_room_access_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_room_access_grants_data_room_id'), ['data_room_id'], unique=False)

    op.create_table('data_room_engagement',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('data_room_id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_room_id'], ['data_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_room_engagement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_room_engagement_data_room_id'), ['data_room_id'], unique=False)

    op.create_table('data_room_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('data_room_id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('folder', sa.String(length=120), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_room_id'], ['data_rooms.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_room_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_room_items_data_room_id'), ['data_room_id'], unique=False)

    op.create_table('data_room_questions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('data_room_id', sa.String(length=32), nullable=False),
    sa.Column('asker', sa.String(length=255), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_room_id'], ['data_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_room_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_room_questions_data_room_id'), ['data_room_id'], unique=False)

    op.create_table('demat_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('security_class_id', sa.String(length=32), nullable=False),
    sa.Column('isin', sa.String(length=16), nullable=True),
    sa.Column('depository', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['security_class_id'], ['security_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demat_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demat_records_entity_id'), ['entity_id'], unique=False)

    op.create_table('distributions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('fund_id', sa.String(length=32), nullable=False),
    sa.Column('dist_no', sa.Integer(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('kind', sa.Enum('RETURN_OF_CAPITAL', 'PROFIT', name='distributionkind'), nullable=False),
    sa.Column('carry_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distributions_fund_id'), ['fund_id'], unique=False)

    op.create_table('document_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_versions_document_id'), ['document_id'], unique=False)

    op.create_table('esop_grants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scheme_id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('stakeholder_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('exercise_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('grant_date', sa.Date(), nullable=False),
    sa.Column('cliff_months', sa.Integer(), nullable=False),
    sa.Column('total_months', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['esop_schemes.id'], ),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('esop_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_esop_grants_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_esop_grants_scheme_id'), ['scheme_id'], unique=False)

    op.create_table('founder_vesting',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('stakeholder_id', sa.String(length=32), nullable=False),
    sa.Column('security_class_id', sa.String(length=32), nullable=False),
    sa.Column('total_shares', sa.Integer(), nullable=False),
    sa.Column('cliff_months', sa.Integer(), nullable=False),
    sa.Column('total_months', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('repurchased', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['security_class_id'], ['security_classes.id'], ),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('founder_vesting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_founder_vesting_entity_id'), ['entity_id'], unique=False)

    op.create_table('issuance_transactions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('security_class_id', sa.String(length=32), nullable=False),
    sa.Column('stakeholder_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('certificate_no', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['security_class_id'], ['security_classes.id'], ),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issuance_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issuance_transactions_entity_id'), ['entity_id'], unique=False)

    op.create_table('lps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('fund_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('commitment', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lps_fund_id'), ['fund_id'], unique=False)

    op.create_table('portfolio_investments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('fund_id', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('instrument', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('ownership_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('invested_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_investments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_investments_fund_id'), ['fund_id'], unique=False)

    op.create_table('resolutions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('meeting_id', sa.String(length=32), nullable=True),
    sa.Column('type', sa.Enum('BOARD', 'ORDINARY', 'SPECIAL', 'CIRCULAR', name='resolutiontype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PASSED', 'FAILED', name='resolutionstatus'), nullable=False),
    sa.Column('passed_date', sa.Date(), nullable=True),
    sa.Column('document_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resolutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resolutions_entity_id'), ['entity_id'], unique=False)

    op.create_table('rights_issues',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('security_class_id', sa.String(length=32), nullable=False),
    sa.Column('ratio_num', sa.Integer(), nullable=False),
    sa.Column('ratio_den', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='rightsissuestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['security_class_id'], ['security_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rights_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rights_issues_entity_id'), ['entity_id'], unique=False)

    op.create_table('rounds',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('instrument', sa.Enum('EQUITY', 'CCPS', 'SAFE', 'CONVERTIBLE_NOTE', name='roundinstrument'), nullable=False),
    sa.Column('pre_money', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('price_per_share', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('security_class_id', sa.String(length=32), nullable=True),
    sa.Column('valuation_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'CLOSED', name='roundstatus'), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['security_class_id'], ['security_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rounds_entity_id'), ['entity_id'], unique=False)

    op.create_table('signature_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'DECLINED', name='signaturestatus'), nullable=False),
    sa.Column('signatories', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signature_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signature_requests_document_id'), ['document_id'], unique=False)

    op.create_table('spv_co_investors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('spv_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('commitment', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('contributed', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['spv_id'], ['spvs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spv_co_investors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spv_co_investors_spv_id'), ['spv_id'], unique=False)

    op.create_table('spv_investments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('spv_id', sa.String(length=32), nullable=False),
    sa.Column('portco_entity_id', sa.String(length=32), nullable=False),
    sa.Column('security_class_id', sa.String(length=32), nullable=False),
    sa.Column('stakeholder_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('issuance_id', sa.String(length=32), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['spv_id'], ['spvs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spv_investments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spv_investments_spv_id'), ['spv_id'], unique=False)

    op.create_table('transfer_transactions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('security_class_id', sa.String(length=32), nullable=False),
    sa.Column('from_stakeholder_id', sa.String(length=32), nullable=False),
    sa.Column('to_stakeholder_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('stamp_duty', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['from_stakeholder_id'], ['stakeholders.id'], ),
    sa.ForeignKeyConstraint(['security_class_id'], ['security_classes.id'], ),
    sa.ForeignKeyConstraint(['to_stakeholder_id'], ['stakeholders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_transactions_entity_id'), ['entity_id'], unique=False)

    op.create_table('workflow_step_instances',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('step_key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('COLLECT_INPUT', 'EXTERNAL_CALL', 'GENERATE_DOCUMENT', 'REQUEST_SIGNATURE', 'RECORD_TRANSACTION', 'TRIGGER_FILING', 'APPROVAL', 'NOTIFY', name='steptype'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETE', 'SKIPPED', name='stepstatus'), nullable=False),
    sa.Column('assignee_role', sa.String(length=32), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('completed_by', sa.String(length=32), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_step_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_step_instances_run_id'), ['run_id'], unique=False)

    op.create_table('drawdown_notices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('call_id', sa.String(length=32), nullable=False),
    sa.Column('fund_id', sa.String(length=32), nullable=False),
    sa.Column('lp_id', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['capital_calls.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['lp_id'], ['lps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drawdown_notices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drawdown_notices_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drawdown_notices_fund_id'), ['fund_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drawdown_notices_lp_id'), ['lp_id'], unique=False)

    op.create_table('esop_exercises',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('grant_id', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('fmv_per_share', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('exercise_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('perquisite_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('issuance_id', sa.String(length=32), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('net_shares', sa.Integer(), nullable=True),
    sa.Column('cashless', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['grant_id'], ['esop_grants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('esop_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_esop_exercises_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_esop_exercises_grant_id'), ['grant_id'], unique=False)

    op.create_table('lp_distributions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('distribution_id', sa.String(length=32), nullable=False),
    sa.Column('fund_id', sa.String(length=32), nullable=False),
    sa.Column('lp_id', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['distribution_id'], ['distributions.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['lp_id'], ['lps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lp_distributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lp_distributions_distribution_id'), ['distribution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lp_distributions_fund_id'), ['fund_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lp_distributions_lp_id'), ['lp_id'], unique=False)

    op.create_table('rights_subscriptions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('rights_issue_id', sa.String(length=32), nullable=False),
    sa.Column('stakeholder_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rights_issue_id'], ['rights_issues.id'], ),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rights_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rights_subscriptions_rights_issue_id'), ['rights_issue_id'], unique=False)

    op.create_table('round_commitments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('round_id', sa.String(length=32), nullable=False),
    sa.Column('investor_name', sa.String(length=255), nullable=False),
    sa.Column('investor_email', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('is_foreign', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('SOFT', 'SIGNED', 'FUNDED', name='commitmentstatus'), nullable=False),
    sa.Column('stakeholder_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('round_commitments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_round_commitments_round_id'), ['round_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round_commitments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_round_commitments_round_id'))

    op.drop_table('round_commitments')
    with op.batch_alter_table('rights_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rights_subscriptions_rights_issue_id'))

    op.drop_table('rights_subscriptions')
    with op.batch_alter_table('lp_distributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lp_distributions_lp_id'))
        batch_op.drop_index(batch_op.f('ix_lp_distributions_fund_id'))
        batch_op.drop_index(batch_op.f('ix_lp_distributions_distribution_id'))

    op.drop_table('lp_distributions')
    with op.batch_alter_table('esop_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_esop_exercises_grant_id'))
        batch_op.drop_index(batch_op.f('ix_esop_exercises_entity_id'))

    op.drop_table('esop_exercises')
    with op.batch_alter_table('drawdown_notices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drawdown_notices_lp_id'))
        batch_op.drop_index(batch_op.f('ix_drawdown_notices_fund_id'))
        batch_op.drop_index(batch_op.f('ix_drawdown_notices_call_id'))

    op.drop_table('drawdown_notices')
    with op.batch_alter_table('workflow_step_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_step_instances_run_id'))

    op.drop_table('workflow_step_instances')
    with op.batch_alter_table('transfer_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_transactions_entity_id'))

    op.drop_table('transfer_transactions')
    with op.batch_alter_table('spv_investments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spv_investments_spv_id'))

    op.drop_table('spv_investments')
    with op.batch_alter_table('spv_co_investors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spv_co_investors_spv_id'))

    op.drop_table('spv_co_investors')
    with op.batch_alter_table('signature_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signature_requests_document_id'))

    op.drop_table('signature_requests')
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rounds_entity_id'))

    op.drop_table('rounds')
    with op.batch_alter_table('rights_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rights_issues_entity_id'))

    op.drop_table('rights_issues')
    with op.batch_alter_table('resolutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resolutions_entity_id'))

    op.drop_table('resolutions')
    with op.batch_alter_table('portfolio_investments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_investments_fund_id'))

    op.drop_table('portfolio_investments')
    with op.batch_alter_table('lps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lps_fund_id'))

    op.drop_table('lps')
    with op.batch_alter_table('issuance_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issuance_transactions_entity_id'))

    op.drop_table('issuance_transactions')
    with op.batch_alter_table('founder_vesting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_founder_vesting_entity_id'))

    op.drop_table('founder_vesting')
    with op.batch_alter_table('esop_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_esop_grants_scheme_id'))
        batch_op.drop_index(batch_op.f('ix_esop_grants_entity_id'))

    op.drop_table('esop_grants')
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_versions_document_id'))

    op.drop_table('document_versions')
    with op.batch_alter_table('distributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distributions_fund_id'))

    op.drop_table('distributions')
    with op.batch_alter_table('demat_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demat_records_entity_id'))

    op.drop_table('demat_records')
    with op.batch_alter_table('data_room_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_room_questions_data_room_id'))

    op.drop_table('data_room_questions')
    with op.batch_alter_table('data_room_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_room_items_data_room_id'))

    op.drop_table('data_room_items')
    with op.batch_alter_table('data_room_engagement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_room_engagement_data_room_id'))

    op.drop_table('data_room_engagement')
    with op.batch_alter_table('data_room_access_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_room_access_grants_data_room_id'))

    op.drop_table('data_room_access_grants')
    with op.batch_alter_table('corporate_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corporate_actions_entity_id'))

    op.drop_table('corporate_actions')
    with op.batch_alter_table('conversion_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversion_events_entity_id'))

    op.drop_table('conversion_events')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_entity_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_counterparty_id'))

    op.drop_table('contracts')
    with op.batch_alter_table('capital_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capital_calls_fund_id'))

    op.drop_table('capital_calls')
    with op.batch_alter_table('buyback_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buyback_transactions_entity_id'))

    op.drop_table('buyback_transactions')
    with op.batch_alter_table('agenda_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agenda_items_meeting_id'))

    op.drop_table('agenda_items')
    with op.batch_alter_table('admin_touchpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_touchpoints_subscription_id'))

    op.drop_table('admin_touchpoints')
    with op.batch_alter_table('admin_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_audits_subscription_id'))

    op.drop_table('admin_audits')
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_entity_id'))

    op.drop_table('workflow_runs')
    with op.batch_alter_table('valuation_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valuation_reports_entity_id'))

    op.drop_table('valuation_reports')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_entity_id'))

    op.drop_table('team_members')
    with op.batch_alter_table('tax_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_records_entity_id'))

    op.drop_table('tax_records')
    with op.batch_alter_table('tax_benefit_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_benefit_applications_entity_id'))

    op.drop_table('tax_benefit_applications')
    with op.batch_alter_table('startup_recognition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_startup_recognition_entity_id'))

    op.drop_table('startup_recognition')
    with op.batch_alter_table('stakeholders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stakeholders_entity_id'))

    op.drop_table('stakeholders')
    with op.batch_alter_table('spvs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spvs_entity_id'))

    op.drop_table('spvs')
    with op.batch_alter_table('service_engagements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_engagements_entity_id'))

    op.drop_table('service_engagements')
    with op.batch_alter_table('security_classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_classes_entity_id'))

    op.drop_table('security_classes')
    with op.batch_alter_table('sbo_register', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sbo_register_entity_id'))

    op.drop_table('sbo_register')
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_entity_id'))

    op.drop_table('registrations')
    with op.batch_alter_table('prospect_investors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prospect_investors_entity_id'))

    op.drop_table('prospect_investors')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_entity_id'))

    op.drop_table('meetings')
    with op.batch_alter_table('investor_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investor_updates_entity_id'))

    op.drop_table('investor_updates')
    with op.batch_alter_table('investor_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investor_access_entity_id'))
        batch_op.drop_index(batch_op.f('ix_investor_access_email'))

    op.drop_table('investor_access')
    with op.batch_alter_table('funds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funds_entity_id'))

    op.drop_table('funds')
    with op.batch_alter_table('financial_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_snapshots_entity_id'))

    op.drop_table('financial_snapshots')
    with op.batch_alter_table('esop_schemes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_esop_schemes_entity_id'))

    op.drop_table('esop_schemes')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_entity_id'))

    op.drop_table('documents')
    with op.batch_alter_table('directors_officers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_directors_officers_entity_id'))

    op.drop_table('directors_officers')
    with op.batch_alter_table('data_rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_rooms_entity_id'))

    op.drop_table('data_rooms')
    with op.batch_alter_table('counterparties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counterparties_entity_id'))

    op.drop_table('counterparties')
    with op.batch_alter_table('convertible_instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_convertible_instruments_entity_id'))

    op.drop_table('convertible_instruments')
    with op.batch_alter_table('compliance_obligations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_obligations_entity_id'))

    op.drop_table('compliance_obligations')
    with op.batch_alter_table('charges_register', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charges_register_entity_id'))

    op.drop_table('charges_register')
    with op.batch_alter_table('admin_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_subscriptions_entity_id'))

    op.drop_table('admin_subscriptions')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_tenant_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('legal_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_entities_tenant_id'))

    op.drop_table('legal_entities')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_table('service_providers')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_user_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
